# Generated by Django 5.2.12 on 2026-03-06 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('prompt', models.TextField()),
                ('required', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('section_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('frequent', 'Frequent'), ('periodic', 'Periodic'), ('test', 'Test')], max_length=20)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DefectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='defect_photos/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.defect')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('asset_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('make', models.CharField(blank=True, help_text='Make of aerial device', max_length=100, null=True)),
                ('model', models.CharField(blank=True, help_text='Model of aerial device', max_length=100, null=True)),
                ('year_of_manufacture', models.CharField(blank=True, max_length=4, null=True)),
                ('insulation_type', models.CharField(blank=True, choices=[('insulating', 'Insulating'), ('non-insulating', 'Non-Insulating')], max_length=20, null=True)),
                ('rated_platform_height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('category', models.CharField(blank=True, choices=[('a', 'Category A'), ('b', 'Category B'), ('c', 'Category C'), ('d', 'Category D'), ('e', 'Category E')], max_length=1, null=True)),
                ('configured_for_electrical_work', models.BooleanField(default=False)),
                ('chassis_insulating_system', models.BooleanField(default=False)),
                ('platform_count', models.PositiveIntegerField(default=1)),
                ('capacity_per_platform', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('capacity_total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('last_qualification_test_date', models.DateField(blank=True, null=True)),
                ('qualification_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('upper_controls_high_resistance', models.BooleanField(default=False)),
                ('material_handling_attachment', models.BooleanField(default=False)),
                ('system_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('control_system_voltage', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('ambient_temp_range', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('manufacturer_city', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer_state', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer_country', models.CharField(blank=True, max_length=100, null=True)),
                ('installed_by', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_year', models.CharField(blank=True, max_length=4, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_vin', models.CharField(blank=True, max_length=17, null=True)),
                ('vehicle_license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, help_text='Job site or specific location', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inspections.customer')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('overall_result', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'N/A')], max_length=10, null=True)),
                ('certificate_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('reference', models.CharField(blank=True, help_text='Inspector reference or job number', max_length=200, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='inspections.equipment')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='inspections.template')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='defect',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='inspections.inspection'),
        ),
        migrations.AddField(
            model_name='defect',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inspections.questiontemplate'),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='inspections.sectiontemplate'),
        ),
        migrations.AddField(
            model_name='sectiontemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='inspections.template'),
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('package', 'Package'), ('certificate', 'Certificate')], max_length=20)),
                ('file', models.FileField(upload_to='generated_docs/%Y/%m/%d/')),
                ('generator_version', models.CharField(default='1.0.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inspections.inspection')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('inspection', 'doc_type', 'generator_version')},
            },
        ),
        migrations.CreateModel(
            name='InspectionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'N/A')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='inspections.inspection')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspections.questiontemplate')),
            ],
            options={
                'ordering': ['question__section__order', 'question__order'],
                'unique_together': {('inspection', 'question')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='sectiontemplate',
            unique_together={('template', 'section_id')},
        ),
        migrations.CreateModel(
            name='InspectionTestModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_modules', to='inspections.inspection')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspections.template')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('inspection', 'template')},
            },
        ),
    ]
