# Generated by Django 5.2.12 on 2026-03-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionanswer',
            name='measurement_value',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Measured value', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='measurement_unit',
            field=models.CharField(blank=True, help_text='Unit for measurement (e.g., kV, mA, lbs)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='question_type',
            field=models.CharField(choices=[('pass_fail', 'Pass/Fail'), ('measurement', 'Measurement')], default='pass_fail', max_length=20),
        ),
    ]
