# Generated by Django 5.2.12 on 2026-03-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiontemplate',
            name='display_group',
            field=models.CharField(blank=True, help_text="Display grouping for PDF reports (e.g., 'Setup', 'Test Execution'). Multiple sections can share the same display_group to appear under one heading.", max_length=200, null=True),
        ),
    ]
