# Generated by Django 5.2.12 on 2026-03-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='reference',
            field=models.CharField(blank=True, help_text='Inspector reference or job number', max_length=200, null=True),
        ),
    ]
