# Generated by Django 5.2.12 on 2026-03-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_inspection_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='ambient_temp_range',
            field=models.CharField(blank=True, help_text='e.g., -20°F to 120°F', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='capacity_per_platform',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='lbs per bucket/platform', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='capacity_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='lbs total (both buckets/platforms)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(blank=True, choices=[('a', 'Category A'), ('b', 'Category B'), ('c', 'Category C'), ('d', 'Category D'), ('e', 'Category E')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='chassis_insulating_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipment',
            name='configured_for_electrical_work',
            field=models.BooleanField(default=False, help_text='Configured for electrical work rubber gloving'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='control_system_voltage',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Volts', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='installed_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='insulation_type',
            field=models.CharField(blank=True, choices=[('insulating', 'Insulating'), ('non-insulating', 'Non-Insulating')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_qualification_test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='material_handling_attachment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipment',
            name='platform_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of platforms/buckets'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='qualification_voltage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='kV', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rated_platform_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Feet', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='system_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='PSI', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='upper_controls_high_resistance',
            field=models.BooleanField(default=False, help_text='Upper controls with high electrical resistance'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='year_of_manufacture',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='make',
            field=models.CharField(blank=True, help_text='Make of aerial device', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, help_text='Model of aerial device', max_length=100, null=True),
        ),
    ]
