# Generated by Django 5.2.12 on 2026-03-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_add_display_group_to_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='definition',
            field=models.JSONField(blank=True, help_text='Full JSON template definition including fields, rules, etc.', null=True),
        ),
    ]
