# Generated by Django 5.2.12 on 2026-03-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_equipment_ambient_temp_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='ambient_temp_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='capacity_per_platform',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='capacity_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='configured_for_electrical_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='control_system_voltage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='platform_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='qualification_voltage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='rated_platform_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='system_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='upper_controls_high_resistance',
            field=models.BooleanField(default=False),
        ),
    ]
